ADM_PARAMS={"acc":"5sf4yt","uv":"57.0","nw":"Bell Canada","dis":"ok","diptr":0.969003995,"cuuid":"","ii":"1201536143766","dicr":0.0132249621,"brl":"g1r0hg","ub":"Chrome","uo":"MacOSX","ud":"Other","ev":"iluvchdse","hhn":"metrics.nt.vc","hhm":"","dilr":0.0180465629};(function(){function db(){try{return sa.now()}catch(a){}return(new Date).getTime()}function ta(a,b){return(b||r).getElementById(a)}function Pb(a,b){b=b||r;if(Ma(b,"querySelectorAll"))return Na(eb(b.querySelectorAll("."+a)));if(Ma(b,"getElementsByClassName"))return Na(eb(b.getElementsByClassName(a)));if(Ma(b,"getElementsByTagName")){for(var d=[],c=b.getElementsByTagName("*"),e=0,f=c.length;e<f;e++)-1<(" "+c[e].className+" ").indexOf(" "+a+" ")&&d.push(c[e]);return Na(d)}return null}function Na(a){return!a||
a&&!a.length?null:a}function eb(a){var b=[];if(!a)return b;for(var d=0,c=a.length;d<c;d++)b.push(a[d]);return b}function Qb(a){var b=h.ADM_PARAMS||{};a=a.replace(/;/g,"%3B").replace(/"/g,"%22").split("?")[1];if(!a)return b;a.replace(/([^=&]+)=([^&]*)/g,function(a,c,e){b[c]=e});b.qsd=a.replace(/&/g,";")+";";return b}function x(a,b,d){var c=function(a){return d(a||h.event)};r.addEventListener?a.addEventListener(b,c,!1):(b="on"+({focus:"focusin",blur:"focusout",DOMContentLoaded:"readystatechange"}[b]||
b),a.attachEvent(b,c));return c}function A(a,b,d){d&&(r.removeEventListener?a.removeEventListener(b,d,!1):(b="on"+({focus:"focusin",blur:"focusout",DOMContentLoaded:"readystatechange"}[b]||b),a.detachEvent(b,d)))}function X(){return g.ub?"Safari"===g.ub:fa.vendor&&-1<fa.vendor.indexOf("Apple")&&-1<D.indexOf("safari")&&-1===D.indexOf("chrome")}function ga(a){var b=0;a="string"===typeof a?h[a]:a;try{a.location.href&&a.document&&(b=1)}catch(d){}return b}function ua(a){if(!ha)return 1;var b=fb(a.document.referrer),
d=fb(a.location.href);return b&&d?d!==b?0:ga(a)?1:0:0}function Rb(a){if(!ha)return 1;var b=0,d=a;a=a.parent;for(var c=0;100>c;)try{if(d==a)return b;b=ua(d);if(!b)break;d=a;a=a.parent;c++}catch(e){break}return 0}function gb(a){var b=[];if(!ha)return[[a]];var d=0,c=a;a=a.parent;for(var e=0;100>e;)try{if(c==a)return b;d=X()?ua(c):ga(a);if(!d)return b;b.push([a,c.frameElement]);c=a;a=a.parent;e++}catch(f){break}return b}function fb(a){if(!a)return!1;var b=r.createElement("a");b.href=a;return b.protocol+
"//"+b.host}function Ma(a,b){return!a||!b||a&&"object"!==typeof a?0:"undefined"!==typeof a[b]}function Y(a){return"undefined"!==typeof a}function hb(a,b,d){try{b(null,a.apply(null,d||[]))}catch(c){b(c)}}function Sb(a,b){return"function"===typeof h.getComputedStyle?h.getComputedStyle(a,b):function(a){this.el=a;this.getPropertyValue=function(b){var c=/(\-([a-z]){1})/g;"float"==b&&(b="styleFloat");c.test(b)&&(b=b.replace(c,function(a,b,c){return c.toUpperCase()}));return a.currentStyle[b]?a.currentStyle[b]:
null};return this}(a,b)}function Oa(a,b,d){var c=0;b=b.split(".");for(var e=b.length;c<e;c++){if(!a||"object"!==typeof a)return d;a=a[b[c]]}return"undefined"===a?d:a}function ia(){for(var a=0;a<arguments.length;a++){var b=arguments[a];if(Y(b))return b}}function Tb(a){for(var b="",d,c,e=0;e<a.length;e++)if(c=a[e][1],c="undefined"!==typeof c?c:"",c=E(E(c)))d=a[e][0],b+=d+"="+c+";";return b}function Ub(a,b){function d(a,c){(c=c||g[a]||"")&&0>b.indexOf(";"+a+"=")&&(b+=a+"="+c+";")}g.ee&&(d("ee"),d("es"),
d("ep"),d("eu"),d("est"));d("tag");1E4<g.cl/1&&(d("cl"),d("pl"),d("cr"),d("mpl"),d("act"),d("pur"),d("mat"),d("dn"),d("aid"),d("sz"),d("emaappid"));if(g.ee||1E4<g.cl/1)d("ed"),d("ec");d("tp");d("ts");d("ii");d("hu");d("cg");d("mg");d("cvd");Oa(q,"m.dv.gvdi")&&d("ivd",q.m.dv.gvdi());Q&&d("ie",Q.ver+"|"+Q.docMode+"|"+(0===h.screenY&&h.innerHeight+1!==h.outerHeight?1:0));d("el",y(db()-Vb));var c=ib+"event/"+a+"/"+(g.clo||g.cl||"_")+"/"+(g.ca||"_")+"."+(g.pl||"_")+"."+(g.cr||"_")+";"+b;Q&&(c+="?"+ja(1E12*
jb()));return c=c.replace(/;dfp=[\d];/,";")}function wa(a,b){var d=g.ev||"iluvchdse";-1!==d.indexOf("a")&&-1===d.indexOf("e")&&(d+="e");if(-1!=d.indexOf(a))return d=Ub(a,b),"1"===g.expr&&"function"===typeof fa.sendBeacon?(fa.sendBeacon(d),d):(new Image(1,1)).src=d}function kb(){if(Wb||"blacklisted"===Xb){var a={};a.status=g.dis||"";a.adm_device_id=g.cuuid||"";a.cgr=g.cgr||"";a.cr=g.dicr||"";a.lr=g.dilr||"";a.ptr=g.diptr||"";h[L](a)}else F(function(){h[L]({status:"timeout",adm_device_id:""})},w(g.uto||
4500))}function lb(a,b){var d=4,c;if(b[a])return a;for(;d--;)if(c=mb[d]+a.charAt(0).toUpperCase()+a.slice(1),b[c])return c}function J(a){for(var b=0,d=0;a&&!isNaN(a.offsetLeft)&&!isNaN(a.offsetTop);)b+=a.offsetLeft,d+=a.offsetTop,a=a.offsetParent;return[b,d]}function Yb(a){for(var b=/relative|absolute|fixed|sticky/,d=J(a),c=[0,0];a;)b.test(Sb(a).position)?(c=J(a),a=null):a=a.offsetParent;return[d[0]-c[0],d[1]-c[1]]}function nb(a){return[a.body.scrollLeft+a.documentElement.scrollLeft,a.body.scrollTop+
a.documentElement.scrollTop]}function ob(a,b){var d=b(a);if(d)return d;for(var c=xa.length-1;0<=c;c--)if(d=b(a,xa[c][0].document)){k=xa[c][0];break}return d}function pb(a){return"string"===typeof a&&"*admcls*"===a.slice(0,8)}function qb(){var a;if(1<I.length||I!=w(I))return pb(I)?(a=ob(I.slice(8),Pb))?a[0]:null:(a=ob(I,ta))?a:null;if(0!=I){if(1==I){for(a=ka;a&&(1!=a.nodeType||"DIV"!=a.tagName);)a=a.previousSibling?a.previousSibling:a.parentNode;if(a)return a}if(5==I){a=new RegExp(ka.id.split("_")[1]);
for(var b=r.getElementsByTagName("object"),d=b.length,c=b[0];d--&&!a.test(c.getAttribute("id")||"");)c=b[d];if(a=c)return a}}return r.body}function Z(a){function b(a,b){c+=a+"="+b+";"}var d=arguments,c="",e=v.length,f;if("l"==a&&q.m.ap)try{f=q.m.ap;var g=f.get();g&&(b("avis",g.join(",")),b("bpx",f.c.n.pos[3]),b("bpy",f.c.n.pos[0]),b("vpw",f.c.vw.w),b("vph",f.c.vw.h))}catch(m){}if("l"==a||"v"==a)b("pd",E(E(Zb))),b("pp",E(E($b)).slice(0,250)),b("sz",l+"x"+n),b("if",""+aa+ya+Pa),b("lt",z(0,ac-bc)),b("al",
cc),b("av",t),b("nd",w(dc)),b("mv",28),sb&&b("fd",sb);if("v"==a){for(;4<e--;)(f=v[e])&&b("v"+e.toString(36),f);Qa+=1;b("vin",Qa);ec();fc();b("vbiv",za.join(""));b("vbin",Ra.join(""))}"h"==a&&(b("hi",Sa),b("ht",d[1]),b("hh",d[2]),b("ha",d[3]));"c"==a&&b("cc",w(d[1])+"x"+w(d[2]));wa(a,c)}function fc(){if(!Aa)for(var a=za.length-1;0<=a;a--)if(za[a]){Aa=1;g.vic&&((new Image(0,0)).src=decodeURIComponent(g.vic));break}}function ec(a){a=a||M[0];for(var b=13;b--;){var d=Ta(b)>=a;za[b]=0+d;Ra[b]=B(9,(Ra[b]||
0)+d)}}function Ta(a,b){b=b||v;var d=q.m.dv.gvb(),c=2===a,e=c?d[1]:d[0],d=[],f;for(f=0;f<e.length;f++)d.push(b[4*a+e[f]]);if(c)return z.apply(null,d);c=0;for(f=d.length-1;0<=f;f--)c+=d[f];return c}function gc(){return function(){var a=[G.scrollLeft+H.scrollLeft,G.scrollTop+H.scrollTop],b=J(p),d=z(0,B(l,a[0]+(k.innerWidth||H.clientWidth)-b[0],b[0]+l-a[0])),a=z(0,B(n,a[1]+(k.innerHeight||H.clientHeight)-b[1],b[1]+n-a[1]));return d*a/(l*n)}}function hc(){function a(){var a=k.parent,b=k.frameElement,
e=w(K[0])||b.clientWidth,b=w(K[1])||b.clientHeight,f=nb(a.document),g=J(k.frameElement),m=z(0,B(e,f[0]+(a.window.innerWidth||H.clientWidth)-g[0],g[0]+e-f[0])),a=z(0,B(b,f[1]+(a.window.innerHeight||H.clientHeight)-g[1],g[1]+b-f[1]));return m*a/(e*b)}function b(){if(!R||R&&!R[1])return 0;var a=R[0],b=R[1],e=w(K[0])||b.clientWidth,f=w(K[1])||b.clientHeight,g=nb(a.document),m=J(b),b=z(0,B(e,g[0]+(a.innerWidth||H.clientWidth)-m[0],m[0]+e-g[0])),a=z(0,B(f,g[1]+(a.innerHeight||H.clientHeight)-m[1],m[1]+
f-g[1]));return b*a/(e*f)}return"1"===g.expr?b:a}function Ba(a,b,d,c){return z(0,B(b-a,a<d?b-d:c-a))}function ic(){return function(){if(!ha)return 0;try{var a=k.mozInnerScreenX-k.screenX,b=k.mozInnerScreenY-k.screenY-S.availTop-(k.toolbar.visible?38:0),d=b+n,c=k.outerHeight-S.availTop,e,f;e=Ba(a,a+l,0,k.outerWidth-S.availLeft);f=Ba(b,d,0,c);return z(0,B(1,e*f/(l*n)))}catch(va){return 0}}}function jc(){function a(){if(G.dispatchEvent){var b=document.createEvent("HTMLEvents");b.initEvent("onmousemove",
!0,!1);G.dispatchEvent(b)}else G.fireEvent&&G.fireEvent("onmousemove");F(a,100)}var b=0,d=0;u.IECursor=x(G,"mousemove",function(a){var c=a.screenX-a.clientX;a=a.screenY-a.clientY;b=Ba(c,c+l,0,S.width-24);d=Ba(a,a+n,100,S.height-50)});a();return function(){return b*d/(l*n)}}function kc(){return function(){var a=0,b=0,d=l-1,c=n-1,e=function(a,b){return C.elementFromPoint(a,b)},f=ja((l-1)/10),g=ja((n-1)/10),m;if(e(0,0)||e(d,0))for(m=10;0<m;m--){if(e(0,m*g-1)||e(d,m*g-1)){b=n/10*m/n;break}}else if(e(0,
c)||e(d,c))for(m=1;11>m;m++)if(e(0,m*g-1)||e(d,m*g-1)){b=(n-n/10*m)/n;break}if(e(0,0)||e(0,c))for(m=10;0<m;m--){if(e(m*f-1,0)||e(m*f-1,c)){a=l/10*m/l;break}}else if(e(d,0)||e(d,c))for(m=1;11>m;m++)if(e(m*f-1,0)||e(m*f-1,c)){a=(l-l/10*m)/l;break}0==a&&0==b&&e(ja(l/2),ja(n/2))&&(a=b=1);a=(a*b).toFixed(2)/1;return isNaN(a)?0:a}}function lc(){var a=/complete|loaded|interactive/;return function(){try{if(!a.test(r.readyState)||"loading"===N.getState()||!N.isViewable()||r.hidden)return 0;if("expanded"===
N.getState())return 1;var b,d=N.getScreenSize(),c=N.getCurrentPosition(),e=c.width,f=c.height,g=c.y+c.height-d.height,m=c.x+c.width-d.width;0>c.y&&(f+=c.y);0<g&&(f-=g);0>c.x&&(e+=c.x);0<m&&(e-=m);b={height:c.height,width:c.width,visibleHeight:f,visibleWidth:e};var h=Math.ceil(b.visibleHeight*b.visibleWidth/(b.height*b.width)*100);return isNaN(h)?0:h/100}catch(Ua){}}}function mc(){return function(){var a=k.$sf.ext.geom();return"object"===typeof a.self&&"number"===typeof a.self.iv?a.self.iv:0}}function nc(){var a=
["getState","isViewable","getScreenSize","getCurrentPosition"];if("object"!==typeof k.mraid)return!1;for(var b=a.length-1;0<=b;b--)if("function"!==typeof k.mraid[a[b]])return!1;return k.mraid}function oc(){var a=J(p);return"1"===g.expr?!!R:aa&&ya&&"00"===a.join("")&&1>=xa.length}function pc(){function a(a){try{a&&(a.sort(function(a,b){return a.time<b.time?-1:a.time>b.time?1:0}),d=a[a.length-1].intersectionRatio)}catch(e){}}var b={threshold:[1,.75,.5,O]},d=0;try{Ca=new h.IntersectionObserver(a,b),
Ca.observe(p)}catch(c){t=t.replace("C","")||"0"}return function(){return d}}function tb(){var a=D.match(/(iphone|ipod|ipad).*applewebkit(?!.*safari)/i),b=[];t="";h.IntersectionObserver&&(b[12]=pc(),t+="C");Pa&&(b[9]=mc(),t+="9");oc()&&(b[8]=hc(),t+="8");N&&(t+="7",b[7]=lc());aa&&Q&&(8<=Q.ver&&(t+="6",b[6]=kc()),8>=Q.ver&&(t+="5",b[5]=jc()));aa||N||(b[4]=gc(),t+="4");"number"==typeof k.mozInnerScreenX&&(b[3]=ic(),t+="3");a||"function"!=typeof requestAnimationFrame||(t+="1",b[1]=qc());""===t&&(t="0",
b[0]=function(){return 1});return b}function ub(){for(var a=3;0<=a;a--){var b=ta("ADM_RAF_"+a+"_"+g.ii,C);b&&b.parentNode.removeChild(b)}}function P(a,b,d){var c=r.createElement("iframe");a="ADM_RAF_"+a+"_"+g.ii;c.id=a;c.marginwidth=c.marginheight=c.frameborder=0;c.width=1;c.style.width=c.style.minWidth=c.style.maxWidth="1px";c.height=8;c.style.height=c.style.minHeight=c.style.maxHeight="8px";c.style.border=0;c.style.position="absolute";c.style.top=d?d+"px":b+"px";c.style.left=b+"px";c.style.opacity=
.01;c.style.zIndex=-1;rc(p).appendChild(c);a=c.contentWindow.document;a.open();a.write('<!DOCTYPE html><script type="text/javascript">(function(){var M=999,w = window,p=+new Date();w.d=M;setTimeout(function l(){var n=(+new Date());if(n-p>M){w.d=M;}else{w.d=Math.min(w.d*2,M);};setTimeout(l,100);},100);function t(){var n=(+new Date());w.d=(w.d+(n-p))/2;p=n;requestAnimationFrame(t);}requestAnimationFrame(t);})();\x3c/script>');a.close();var e=0;x(c,"mousemove",function(){e=0<e?0:8;c.style.top=d+e+"px"});
return c.contentWindow.window}function rc(a){for(var b=0,d=a;50>b;){b++;var c;a:{c="OBJECT EMBED IMG PARAM SOURCE TRACK".split(" ");for(var e=d.nodeName,f=c.length-1;0<=f;f--)if(e===c[f]){c=!1;break a}c=!0}if(c)return d;if(d===a.parentNode)return vb;d=a.parentNode}}function qc(){ub();var a=1E3/900,b=1-O,d=0,c=0,e=0,f=Yb(p),h=P("0",-9E4),m=[P("1",y(.5*l)+f[0],y(.5*n)+f[1]),P("2",f[0]+1,f[1]+1),P("3",y(l)+f[0]-1,y(n)+f[1]-1)],k=[P("4",y(l*O)+f[0],y(n*O)+f[1]),P("5",y(l*b)+f[0],y(n*O)+f[1]),P("6",y(l*
O)+f[0],y(n*b)+f[1]),P("7",y(l*b)+f[0],y(n*b)+f[1])],Ua=[],q=[];return function(){if("1"===g.expr&&d>a)return t=t.replace("1","")||"0",[0,0];if(100>h.d)return d++,[0,0];for(var b,f=m.length-1;0<=f;f--)b=m[f].d,100>b&&("1"!==g.expr||"1"===g.expr&&Ua[f]!==b)&&(c+=1),Ua[f]=b;for(f=k.length-1;0<=f;f--)b=k[f].d,100>b&&("1"!==g.expr||"1"===g.expr&&q[f]!==b)&&(e+=1),q[f]=b;var f=c,va=e;e=c=0;switch(f){case 3:b=1;break;case 2:b=.51;break;case 1:b=.49;break;case 0:b=0;break;default:b=0}switch(f+va){case 7:f=
1;break;case 6:f=.99;break;case 4:f=.51;break;case 3:f=.49;break;default:f=0}return[b,f]}}function Va(a){function b(a){if(!(w(g.mhe||9E9)<Sa)){switch(a){case "i":ba+=100;break;case "o":ba+=10;break;default:a="m",ba+=1}Da.push(a+":"+d+"x"+c)}}var d=y(a.clientX),c=y(a.clientY);a=a.type;var e=+new Date,f=e-wb;la=e;ma||(ma=e);"mouseover"==a&&b("i");"mouseout"==a&&b("o");"mousemove"==a&&(100>f&&(clearTimeout(xb),xb=F(b,150)),wb=e);yb()}function yb(){function a(){var a=la-ma;switch(ba){case 111:return 300>
a?1:0;case 11:return 200>a?1:0;default:return 0}}clearTimeout(zb);zb=F(function(){Da.length&&(a()||(Sa+=1,Z("h",la-ma,"a",E(Da.join(",")))),ba=0,ma=la=null,Da=[])},900)}function Wa(a){if(T){var b=[9,1,2,12,3,6,5,8,4,7];if(T[11]){var d=Ta(11,a);if(d)return d?d/1E3:0}for(d=b.length-1;0<=d;d--){var c=b[d];if(T[c])return(a=Ta(c,a))?a/1E3:0}return 0}}function na(a){var b=z.apply(null,v.slice(4)),d=900<b,c="0"!=t;Aa||(d=1E3*Wa()>M[0]);clearTimeout(Ea);var e=a;g.expr&&(e=a&&Aa);if(c&&d||e){if(Qa>=w(g.mve||
9E9)){clearInterval(Xa);return}Z("v");Ab();ca=B(3E4,2*ca)}Ya||(0===b&&(ca=1E3),da=+new Date,Ea=F(na,ca))}function oa(){var a=+new Date,b=a-da,d=t.length,c,e;try{c=ia(k&&k.screenX,k&&k.screenLeft),e=Y(c)?-3E4>c:0}catch(va){e=1}if(q&&q.m.bo&&q.m.bo.io||!U||e||"1"===g.expr&&(0>b||800<b))return"1"===g.expr&&(da=+new Date),a;for(Bb=v.slice(0);d--;)if(e=w(t.charAt(d),36),c=T[e])c=c(),1===e&&(c="1"===g.expr?c[1]:c[0]),"number"==typeof c?(c=c<O?-1:.5>c?0:.75>c?1:1>c?2:3,0<=c&&(v[4*e+c]+=b)):(v[4*e+0]+=0<
c[0]?b:0,v[4*e+1]+=0<c[1]?b:0,v[4*e+2]+=0<c[2]?b:0,v[4*e+3]+=0<c[3]?b:0);if(q.m.sdkBridge.l){b=Fa;c=Cb;var f,d=v;for(e=Bb;c--;)"number"===typeof d[c]&&(f=d[c]-e[c],0>f||isNaN(f)||(b[c]="number"===typeof b[c]?b[c]+f:f))}da=a}function Ga(){U=1;oa()}function Db(){250>+new Date-Ha&&(Z("r"),Ha=0);na();oa();U=0}function Ab(a){var b=Cb;for(a=a||v;b--;)a[b]=0}function Za(){Ya||(Ya=1,Z("u"),na(1))}function sc(a){K=a||[0,0];l=w(K[0])||(p?p.clientWidth:0);n=w(K[1])||(p?p.clientHeight:0);"0"!=g.mve&&(T=tb())}
function tc(){na(1);oa();q.s=0;var a=ta("ampix"+g.ii+0,C),b=ta("ampix"+g.ii+1,C);a?a.parentNode.removeChild(a):null;b?b.parentNode.removeChild(b):null;ub();A(p,"mouseover",u.mouseover);A(p,"mouseout",u.mouseout);A(p,"mousemove",u.mousemove);A(p,"mousedown",u.mousedown);A(k,"beforeunload",u.beforeunload);A(k,"unload",u.unload);A(G,"mousemove",u.IECursor);A(k,"resize",u.resize);A(k,"scroll",u.scroll);A(C,Ia,u[Ia]);clearTimeout(Ea);clearInterval(Xa);Za();Ca&&Ca.disconnect()}function uc(a){if(!V)return 0;
a=gb(a);for(var b,d=0,c=a.length;d<c;d++){b=a[d];if(!b||b&&!b[1])return 0;var e=J(b[1]).join("");if(l+""+n!==b[1].offsetWidth+""+b[1].offsetHeight||"00"!==e&&d!==c-1)return 0}return b}function Eb(){if(!Fb&&q.s)if(!p&&pb(I))F(function(){q.s&&(p=qb(),Eb())},1E3);else{Fb=1;C=k.document;G=C.body;H=C.documentElement;aa=k.parent==k?0:1;ya=X()?ua(k):ga(k.parent);U=Y(C[Gb])?!C[Gb]:1;try{"function"===typeof k.$sf.ext.geom&&(Pa=1)}catch(a){}N=nc();l=w(K[0])||(p?p.clientWidth:0);n=w(K[1])||(p?p.clientHeight:
0);R=uc(k);q.m.dv.i(l*n,0);M=q.m.dv.gvd();ca=1E3;O="1"===g.expr&&M&&M[1]&&25<M[1]&&50>M[1]?M[1]/100:.25;"0"!=g.mve&&(T=tb(),Ab(),u.resize=x(k,"resize",Ga),u.scroll=x(k,"scroll",Ga),Xa=vc(function(){if("1"===g.expr&&wc){var a;if(V){a=h.top.document.hasFocus()?1:0;var b=a!==U;U=a;a=b}else a=void 0;a?U?(da=+new Date,Ga()):Db():oa()}else oa()},80),Ea=F(na,ca));T.length&&$a&&(u[Ia]=x(C,Ia,function(){"visible"===C[$a]?(da=+new Date,Ga()):Db()}));u.beforeunload=x(k,"beforeunload",Za);u.unload=x(k,"unload",
Za);u.mouseover=x(p,"mouseover",Va);u.mouseout=x(p,"mouseout",Va);u.mousemove=x(p,"mousemove",Va);"IFRAME"!=p.tagName&&(u.mousedown=x(p,"mousedown",function(a){var b,d=[G.scrollLeft+H.scrollLeft,G.scrollTop+H.scrollTop];b=a.clientX+d[0];a=a.clientY+d[1];d=J(p);b=[b-d[0],a-d[1]];Ha=+new Date;Z("c",b[0],b[1]);ba+=1E3;la=Ha;yb()}),Z("l"));q.m.metrics.r=sc;q.m.metrics.d=tc}}var q={v:"22a0c2d",s:1,m:{}},h=this,r=h.document,xc=h.location,w=parseInt,pa=Math,B=pa.min,z=pa.max,ja=pa.floor,y=pa.round,jb=pa.random,
sa=h.performance,Vb=db(),Hb=h.ActiveXObject,E=h.encodeURIComponent,S=h.screen,fa=h.navigator,vb=r.body,D=fa.userAgent.toLowerCase(),Q=function(){var a=!!h.MSInputMethodContext||!!D.match(/trident\/7.\d/),b=!!D.match(/edge\/\d/),d=!!h.attachEvent||a||b,c=-1<D.indexOf("msie 7.0"),e=!1,f=D.match(/msie ([0-9]{1,}[.0-9]{0,})/);try{b?e=parseFloat(D.match(/edge\/([0-9]{1,})/)[1]):a?e=11:f&&(e=parseFloat(f[1]))}catch(va){e=!1}d&&c&&!a&&(-1<D.indexOf("trident/6.0")?e=10:-1<D.indexOf("trident/5.0")?e=9:-1<
D.indexOf("trident/4.0")&&(e=8));return d&&{docMode:r.documentMode||0,ver:e}}(),vc=h.setInterval,F=h.setTimeout,ha=h.parent==h?0:1,mb=["webkit","moz","o","ms"],Ib=xc.protocol,ab=h.ADM_PARAMS&&h.ADM_PARAMS.hhn,qa="https://metrics.nt.vc/",Ja="http://metrics.nt.vc/",ib="http:"===Ib?Ja:qa;ab&&(qa="https://"+ab+"/",Ja="http://"+ab+"/",ib="http:"===Ib?Ja:qa);var Ka=h.JSON&&h.JSON.stringify||function(){var a={'"':'\\"',"\\":"\\\\","\n":"\\n","\r":"\\r"},b=function(b){return a[b]||"\\u"+(b.charCodeAt(0)+
65536).toString(16).substr(1)},d=/[\\"\u0000-\u001F\u2028\u2029]/g;return function(a){var c,f=typeof a;if(null==a)a="null";else if("string"===f)a='"'+a.replace(d,b)+'"';else if("number"!==f&&"boolean"!==f)if(f=[],"[object Array]"===Object.prototype.toString.call(a)){for(c=a.length;0<c--;)f[c]=Ka(a[c]);a="["+f.join(",")+"]"}else{for(c in a)f.push(Ka(c)+":"+Ka(a[c]));a="{"+f.join(",")+"}"}return""+a}}(),g,ka=function(){for(var a=/\/metrics.*\.js\??/,b=new RegExp(qa),d=new RegExp(Ja),c=r.getElementsByTagName("script"),
e=[],f=-1,g=c.length;++f!==g;e[f]=c[f]);e.push(r.currentScript);for(c=e.length;0<c--;)if((f=e[c])&&f.src&&a.test(f.src)&&!f.getAttribute("adm-init")&&(b.test(f.src)||d.test(f.src)))return f}();if(ka){ka.setAttribute("adm-init","1");g=Qb(ka.src);var V=X()?Rb(h):ga("top");X()?ua(h):ga("parent");var xa=gb(h),Jb;Jb=V?h.top.location.href:r.referrer;var Kb=Jb.match(/^https?\:\/\/([^\/:?#]+)((?:[^?#]+))/i)||[void 0,"",""],Zb=Kb[1],$b=Kb[2];try{new Hb("Microsoft.XMLHTTP")}catch(a){Hb=0}var bb="uuid_cb",W=
h[bb],Wb=g.cuuid,Xb=g.dis,L=("_cb_"+jb()).replace(".",""),La=0;W||(bb+=g.ii||"",W=h[bb]);!W&&"1"===g.ifu&&h.parent.postMessage&&(h[L]=function(a,b){if(!La){La=1;try{var d={};d.ii=g.ii;d.u=a;d.c=b;h.parent.postMessage(Ka(d),"*")}catch(c){}}},kb());W&&(h[L]=function(a,b){!La&&(La=1,g.ifp||-1!==g.ev.indexOf("f"))&&("object"===typeof a?W(a.adm_device_id,a.cgr):W(a,b))},kb());if(1==g.ifp){if(h[L])if(h.parent.postMessage)var yc=x(h,"message",function(a){try{var b=a.message?"message":"data",d="string"===
typeof a[b]?JSON.parse(a[b]):{};if(""+d.ii===""+g.ii){if("object"===typeof d.u)h[L](d.u.adm_device_id,d.u.cgr);else h[L](d.u,d.c);A(h,"message",yc)}}catch(c){}});else h[L]();var ea=r.createElement("iframe");ea.src=qa+"metrics.html?ii="+g.ii+"&cl="+g.cl+"&ev=f&ifu="+(W?1:0);ea.style.width=ea.style.height=0;ea.style.position="absolute";ea.frameBorder=0;vb.appendChild(ea)}(function(a){function b(){e||(e=1,F(function m(){if("undefined"!==typeof Fa&&"function"===typeof Wa){var a=Wa(Fa);Fa=[];q.m.sdkBridge.l&&
(1===q.m.sdkBridge.l?d(h,a):2===q.m.sdkBridge.l&&f&&d(f,a));F(m,500)}},500))}function d(a,b){try{a.postMessage(JSON.stringify({ii:g.ii,"adm-cmd":4,data:b}),"*")}catch(rb){}}function c(a,b){try{a.postMessage(JSON.stringify({guid:b,"adm-cmd":0,data:g}),"*")}catch(rb){}}var e,f;q.m.sdkBridge={l:0};x(h,"message",function(a){if(a&&(!a||a.source)){var d=a.data;try{d=JSON.parse(a.data)}catch(rb){}if(d&&d["adm-cmd"])switch(d["adm-cmd"]){case 1:c(h,d.guid);q.m.sdkBridge.l=1;b();break;case 2:f=a.source;f&&
(c(f,d.guid),q.m.sdkBridge.l=2,b());break;case 3:g.ii===d.ii&&wa(d.type,d.params)}}})})();(function(a){var b={n:{el:null,pos:[]},vw:{h:null,w:null},a:[[0,a,160,0],[160,200,a,0],[160,a,a,200],[160,a,a,a],[a,a,a,0],[a,Infinity,Infinity,-Infinity],[-Infinity,Infinity,0,-Infinity],[0,Infinity,a,a],[0,0,a,-Infinity]]};q.m.ap={q:[],get:function(){if("undefined"===typeof p||ha&&!V)return!1;b.n.el=aa&&ya?k.frameElement:p;var a=h.top;b.vw.h="undefined"!==typeof a.innerHeight?a.innerHeight:a.document.documentElement.clientHeight;
b.vw.w="undefined"!==typeof a.innerWidth?a.innerWidth:a.document.documentElement.clientWidth;var c=J(b.n.el),a=c[1],c=c[0];b.n.pos=[a,c+l,a+n,c];b.a[0][1]=b.vw.w;b.a[1][2]=b.vw.h-160;b.a[2][1]=b.vw.w-200;b.a[2][2]=b.vw.h-160;b.a[3][1]=b.vw.w;b.a[3][2]=b.vw.h-160;b.a[3][3]=b.vw.w-200;b.a[4][0]=b.vw.h-160;b.a[4][1]=b.vw.w;b.a[4][2]=b.vw.h;b.a[5][0]=b.vw.h;b.a[7][2]=b.vw.h;b.a[7][3]=b.vw.w;b.a[8][2]=b.vw.h;a=[];for(c=0;c<b.a.length;c++){var e,f=b.a[c];e=z(0,B(b.n.pos[1],f[1])-z(b.n.pos[3],f[3]));f=z(0,
B(b.n.pos[2],f[2])-z(b.n.pos[0],f[0]));e=(e*f*100/(n*l)).toFixed(0)/1;isNaN(e)||a.push(e)}return a},c:b}})();(function(){function a(){b();e||F(a,1E3)}function b(){var a=h,b=r,e=S;V&&(a=h.top,b=a.document,e=a.screen);var g=e.availWidth||e.width,k=e.availHeight||e.height,l=a,n=ia(l.screenX,l.screenLeft),l=ia(l.screenY,l.screenTop),e=[n-e.availLeft,l-e.availTop],l=e[0],e=e[1],n=g,p=k;V&&(n=ia(a.innerWidth,Oa(b,"documentElement.clientWidth")),p=ia(a.innerHeight,Oa(b,"documentElement.clientHeight")));
a=[n,p];b=a[0];a=a[1];n=90*b/100;p=90*a/100;if(!isNaN(l)&&!isNaN(e)&&b&&a){g=0>l&&-1*l>n||0<=l&&l+b-g>n||!d&&0>e&&-1*e>p||!d&&0<=e&&e+a-k>p;if(g!==q.m.bo.io)for(k=0;k<c.length;k++)c[k](g);q.m.bo.io=g}}var d=X(),c=[],e=0;q.m.bo={i:function(){Y(S.availLeft)&&(e=0,hb(b,function(b){b||a()}))},io:!1,cbs:c,d:function(){e=1}};hb(b,function(){})})();(function(){function a(a){if(f){for(var b=[],c=0;c<a.length;c++){var d=a[c],e=d[0],d=d[1],g=f[1];g<=e?b.push(c):g>e&&g<d&&b.push(c)}return b}}function b(a){var b=
c[g.cvd]||c[0];return 1===a?b[a]:b[a]?b[a]:c[0][a]}var d=[[[25,50],[50,75],[75,100],[100,101]],[[50,51],[50,51],[50,51],[50,51]]],c=[[[900,50],[900,30,242500],[1900,50]],[[1E3,50],[1E3,30,242500],[2E3,50]],[[5E3,50],null,null],[[5E3,100],null,null],[[1E3,25],null,null]],e,f,h;q.m.dv={i:function(c,g){var k=b(1),k=k&&k[2];e=g?2:k&&c&&c>=k?1:0;f=b(e);h=[a(d[0]),a(d[1])]},gvdi:function(){return e},gvd:function(){return f},gvb:function(){return h},d:c,sd:function(a){c=a}}})();var Cb=52,Fb=0,bc=sa&&sa.timing.navigationStart||
+new Date,cc=sa?1:0,ac=+new Date,dc=500,Ya=0,Qa=0,za=[],Ra=[],u={},Aa=0,sb=0,I=g.cn||"1",K=(g.sz||"0x0").split("x");X();var Da=[],t="0",$a=lb("visibilityState",r),Gb=lb("hidden",r),Ia=function(a){for(var b=4,d;a&&b--;)if(d=mb[b],0===a.indexOf(d))return d;return""}($a)+"visibilitychange",Ha=0,da=+new Date,v=[0],Bb,Fa=[];Y(r.hasFocus);var T,Ea,Xa,Sa=0,ba=0,xb,zb,wb,la,ma,wc=Y(r.hasFocus),k=h,p=qb(),C,G,H,aa,ya,R,N,Pa=0,U,l,n,O,M,ca,Ca;q.m.metrics={q:[],r:function(){},d:function(){}};Eb();(function(a){function b(){try{V&&
(e.w=h.top)}catch(zc){}if(e.w){e.wh="undefined"!==typeof e.w.innerHeight?e.w.innerHeight:e.w.document.documentElement.clientHeight;var a=e.w.document.body,b=e.w.document.documentElement;e.ph=Math.max(a.scrollHeight,a.offsetHeight,b.clientHeight,b.scrollHeight,b.offsetHeight)}else e.w=null}function d(){var a=(100*(g[k]+e.wh)/e.ph).toFixed(0),a=a-a%10;a>f&&(wa("s","spos="+a+";"),f=a)}function c(a,b,c){var d;return function(){var e=this,f=arguments,g=c&&!d;clearTimeout(d);d=F(function(){d=null;c||a.apply(e,
f)},b);g&&a.apply(e,f)}}var e={w:null,wh:null,ph:null},f=0,g,k,l={};q.m.scrollDepth={q:[],d:function(){e.w&&(A(e.w,"scroll",l.scroll),A(e.w,"resize",l.resize))}};b();e.w&&("pageXOffset"in e.w?(g=e.w,k="pageYOffset"):(g=e.w.document.documentElement,k="scrollTop"),l.scroll=x(e.w,"scroll",c(d,600)),l.resize=x(e.w,"resize",c(b,200)),d())})();var Lb=h["dap"+g.ii],ra=g.dapc,Mb="";if(Lb&&ra){for(var ra=ra.split(","),cb,Nb,Ob=ra.length;Ob--;)cb=ra[Ob],Nb=(Lb[cb]||"").split("|",1)[0],Mb+=E(E(cb))+"%3D"+E(E(Nb))+
"%26";wa("d",Tb([["dpd",Mb]]))}}})();
